### PR TITLE
assets/worker: do not user host network

### PR DESCRIPTION
**Pull request by marquiz**
No need for nfd-worker to use hostNetwork, anymore.

### CODE REVIEW

**Review by ArangoGutierrez — APPROVED** [review]
Can we merge this after the big refactoring PR? rebasing over this will be painful 

/hold

**Comment by marquiz** [comment]
Rebased
/unhold

**Comment by ArangoGutierrez** [comment]
Needs rebase ;P

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Pull request merged**
