### PR TITLE
setting finalizer on the NFD CR

### PR DESCRIPTION
**Pull request by yevgeny-shnaidman**

### CODE REVIEW

**Review by marquiz — COMMENTED** [review]
Thanks @yevgeny-shnaidman. Looks clean to me, albeit incomplete. So one question: is the other parts of the finalizer handling (`hasFinalizer` et al) supposed to be added by further PRs?

**Comment by yevgeny-shnaidman** [comment]
> Thanks @yevgeny-shnaidman. Looks clean to me, albeit incomplete. So one question: is the other parts of the finalizer handling (`hasFinalizer` et al) supposed to be added by further PRs?

@marquiz  my intention was to do it in a different PR, but you are right, it will be cleaner and clearer to do it in the same one. Added the hasFinalizer implementation.  The finalization flow will be added in a different PR

**Review by marquiz — APPROVED** [review]
Thanks @yevgeny-shnaidman, looks good 
/assign @ArangoGutierrez

**Comment by yevgeny-shnaidman** [comment]
ping @ArangoGutierrez

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Pull request merged**
