### PR TITLE
Pivoting to new operator implementation

### PR DESCRIPTION
**Pull request by yevgeny-shnaidman**
Starting from this commit, operator will use the new controller implementation. The old implementation code will be deleted in the subsequent PRs

### CODE REVIEW

**Comment by marquiz** [comment]
Thanks @yevgeny-shnaidman for the PR. I'll check it in detail a bit later. First question (after a 30s skim-through): are the logger changes related/dependent on this (or could they be a separate PR)?

**Comment by yevgeny-shnaidman** [comment]
> Thanks @yevgeny-shnaidman for the PR. I'll check it in detail a bit later. First question (after a 30s skim-through): are the logger changes related/dependent on this (or could they be a separate PR)?

They are dependent on switching to the new controller. Unless we do them, we will see some warnings in the manager log

**Comment by marquiz** [comment]
> They are dependent on switching to the new controller. Unless we do them, we will see some warnings in the manager log

Kinda useless nitting, but where do we get warnings? Looking at the PR now we only change logger in main.go which shouldn't affect any other parts of the codebase 🧐 So it looks to me like the logger changes could/should be just a separate PR.

**Comment by yevgeny-shnaidman** [comment]
> > They are dependent on switching to the new controller. Unless we do them, we will see some warnings in the manager log
> 
> Kinda useless nitting, but where do we get warnings? Looking at the PR now we only change logger in main.go which shouldn't affect any other parts of the codebase 🧐 So it looks to me like the logger changes could/should be just a separate PR.

We get the warning in the manager log, but those warnings are coming from the controller-runtime code. I can split this PR into 2 ( first the actual pivot and then the logging PR), but i wanted to keep it altogether so that after this PR the operator can be seen deployed and running with logs.

**Review by marquiz — APPROVED** [review]
Thanks @yevgeny-shnaidman. I'm good to merge this as is 

/assign @ArangoGutierrez

**Comment by yevgeny-shnaidman** [comment]
ping @ArangoGutierrez

**Comment by ArangoGutierrez** [comment]
> ping @ArangoGutierrez

Sorry I was traveling last week, will review this one this week

**Comment by yevgeny-shnaidman** [comment]
ping @ArangoGutierrez

**Pull request merged**
