### PR TITLE
Fix golangci-lint verify

### LINKED ISSUE #23: Fix golangci-lint verify
Verify is failing 
`./scripts/test-infra/verify.sh`
output
```bash
pkg/config/config.go:29:5: `log` is unused (deadcode)
var log = logf.Log.WithName("config")
    ^
pkg/controller/nodefeaturediscovery/nodefeaturediscovery_resources.go:38:5: `manifests` is unused (deadcode)
var manifests []assetsFromFile
    ^
pkg/controller/nodefeaturediscovery/nodefeaturediscovery_controller.go:141:10: Error return value of `nfd.init` is not checked (errcheck)
        nfd.init(r, instance)
                ^
pkg/controller/nodefeaturediscovery/nodefeaturediscovery_state.go:49:10: Error return value of `addState` is not checked (errcheck)
        addState(n, "/opt/nfd/master")
                ^
pkg/controller/nodefeaturediscovery/nodefeaturediscovery_state.go:50:10: Error return value of `addState` is not checked (errcheck)
        addState(n, "/opt/nfd/worker")
                ^
pkg/controller/nodefeaturediscovery/nodefeaturediscovery_state.go:78:2: S1008: should use 'return n.idx == len(n.controls)' instead of 'if n.idx == len(n.controls) { return true }; return false' (gosimple)
        if n.idx == len(n.controls) {
        ^
pkg/config/config.go:22:2: SA1019: package sigs.k8s.io/controller-runtime/pkg/runtime/log is deprecated: use pkg/log  (staticcheck)
        logf "sigs.k8s.io/controller-runtime/pkg/runtime/log"
        ^
cmd/manager/main.go:35:2: SA1019: package sigs.k8s.io/controller-runtime/pkg/runtime/log is deprecated: use pkg/log  (staticcheck)
        logf "sigs.k8s.io/controller-runtime/pkg/runtime/log"
        ^
cmd/manager/main.go:36:2: SA1019: package sigs.k8s.io/controller-runtime/pkg/runtime/signals is deprecated: use pkg/manager/signals instead.  (staticcheck)
        "sigs.k8s.io/controller-runtime/pkg/runtime/signals"
        ^
pkg/controller/nodefeaturediscovery/nodefeaturediscovery_state.go:73:14: func `NFD.validate` is unused (unused)
make: *** [Makefile:70: ci-lint] Error 1
```

### PR DESCRIPTION
**Pull request by A-Hilaly**
Fixes #23 

FIx golangci-lint verify
- Fix zap logger creation
- Light to changes to `nodefeaturediscovery.NFD` struct
- Remove unused variables/methods

```bash
make verify                                                                      
gofmt OK
golangci-lint run --timeout 5m0s
```

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
Nice!  looks like prow verify is happy, going to test this locally

**Review by ArangoGutierrez — APPROVED** [review]
tested on a kubernetes 1.17 cluster, it works
/lgtm

**Review by marquiz — APPROVED** [review]
Nice @A-Hilaly ! Thank you for the patch 👍 

/approve

**Pull request merged**
