### PR TITLE
Updated the links in contributing page

### PR DESCRIPTION
**Pull request by vaibhav2107**
Ref : #102

### CODE REVIEW

**Comment by vaibhav2107** [comment]
Hi @ArangoGutierrez , @zvonkok,
Could you please have a look.

**Comment by ArangoGutierrez** [comment]
> Hi @ArangoGutierrez , @zvonkok, Could you please have a look.

Hi @vaibhav2107 thanks for helping! 

please first fix your CLA before moving forward
/hold

**Comment by vaibhav2107** [comment]
Hi @ArangoGutierrez,
I have already signed the CLA, but I think this EasyCLA is optional. 
Please refer this [comment.](https://github.com/kubernetes/test-infra/pull/24381#issuecomment-970909344)

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Comment by vaibhav2107** [comment]
Hi @ArangoGutierrez , 
The Easy CLA thing is fixed now, so could we remove the hold label.

**Review by ArangoGutierrez — APPROVED** [review]
Thanks for this @vaibhav2107 !!
/lgtm

**Comment by vaibhav2107** [comment]
@ArangoGutierrez Thanks for the approval.

**Pull request merged**
