### PR TITLE
scripts/test-infra: add unit-tests.sh

### PR DESCRIPTION
**Pull request by marquiz**
NOTE: another option would be to make this completely separate prow job

### CODE REVIEW

**Comment by marquiz** [comment]
Rebased
/remove-lifecycle stale

**Comment by marquiz** [comment]
Let's see if prow obeys my late'ish hold. But it'd be good to sync up with https://github.com/kubernetes/test-infra/pull/32037

Merge the test-infra first. Then this PR

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Pull request merged**
