### PR TITLE
Add BASE_IMAGE_FULL build arg

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
This patch :
- Bumps base go image to 1.16.6
- updates second stage image to be consistent with NFD via build args

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
> Looks basically good. Just pondering the naming of the variable, are you planning to have a `minimal` image similar to NFD (operand)? If not, we could drop the `_FULL` suffix from it.

https://github.com/ArangoGutierrez/node-feature-discovery-operator/commit/642bf6a351456622cda9e69fbbac3736640411f2

**Comment by marquiz** [comment]
nit: the title of this PR is misleading. I'd change it to something like **Add BASE_IMAGE_FULL build arg**

**Review by marquiz — COMMENTED** [review]
I think we'd better add the minimal image in a separate PR.

Need to add CI support (build-image and push-image) plus preferably mention that in the documentation, too.

Talking about CI, should we have an `images` Makefile target building both images and use that in `scripts/test-infra/build-image.sh` 🤔

**Comment by ArangoGutierrez** [comment]
> I think we'd better add the minimal image in a separate PR.
> 
> Need to add CI support (build-image and push-image) plus preferably mention that in the documentation, too.
> 
> Talking about CI, should we have an `images` Makefile target building both images and use that in `scripts/test-infra/build-image.sh` thinking

OK, removed the commit, will turn that one into a PR, + documentation + CI (in a single PR)

**Review by marquiz — APPROVED** [review]
Looks good, now

/lgtm

**Comment by ArangoGutierrez** [comment]
Follow up PR https://github.com/kubernetes-sigs/node-feature-discovery-operator/pull/82

**Pull request merged**
