### PR TITLE
Cherry/0.4.2

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Cherry-picks from:
 - https://github.com/kubernetes-sigs/node-feature-discovery-operator/pull/141
 - https://github.com/kubernetes-sigs/node-feature-discovery-operator/pull/144
 - https://github.com/kubernetes-sigs/node-feature-discovery-operator/pull/139

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
```bash
[eduardo@fedora-workstation node-feature-discovery-operator]$ make verify-gofmt 
gofmt OK
[eduardo@fedora-workstation node-feature-discovery-operator]$ ./scripts/verify-gofmt.sh 
gofmt OK
[eduardo@fedora-workstation node-feature-discovery-operator]$ make verify
gofmt OK
golangci-lint run --timeout 5m0s
```


/test pull-node-feature-discovery-operator-verify

**Review by marquiz — APPROVED** [review]
/lgtm

**Pull request merged**
