### PR TITLE
Include the operator-sdk bundle as repo payload

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
It has become common practice to include the bundle folder in the repo this patch is generated by running "make bundle", moving forward updating the bundle will be part of the release process.

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
Part of #174

**Review by marquiz — COMMENTED** [review]
Thanks @ArangoGutierrez. 

Could you also include the scripts, makefile rule(s) or whatever is needed to update the bundle? And update the release process in ´.github/ISSUE_TEMPLATE/release.md` to include this (if it's needed)?

Also, you could split this PR into two commits: the first one introducing the tooling to update the bundle (Dockerfile et al) and the second commit being the "auto-generated" content, i.e. new content added by running that tooling

**Comment by ArangoGutierrez** [comment]
> 

Hey Markus thanks for the review, sure to the first part, working on that now, but the scond part is already there, this PR is basically generated by running `make bundle VERSION=x.y.z` so the tooling is there already.

**Comment by marquiz** [comment]
Are you planning to address the documentation in this PR?

BTW, just out of curiosity, I tried running `make bundle` locally. Of course, it didn't work and errored out because of incompatible version of operator-sdk. Any thoughts how to address these annoying skew problems? Doing containerized build for make bundle? At least we need to document what versions of tools are needed

**Comment by ArangoGutierrez** [comment]
> Are you planning to address the documentation in this PR?
> 
> BTW, just out of curiosity, I tried running `make bundle` locally. Of course, it didn't work and errored out because of incompatible version of operator-sdk. Any thoughts how to address these annoying skew problems? Doing containerized build for make bundle? At least we need to document what versions of tools are needed



> Are you planning to address the documentation in this PR?
> 
> BTW, just out of curiosity, I tried running `make bundle` locally. Of course, it didn't work and errored out because of incompatible version of operator-sdk. Any thoughts how to address these annoying skew problems? Doing containerized build for make bundle? At least we need to document what versions of tools are needed



> Are you planning to address the documentation in this PR?
> 
> BTW, just out of curiosity, I tried running `make bundle` locally. Of course, it didn't work and errored out because of incompatible version of operator-sdk. Any thoughts how to address these annoying skew problems? Doing containerized build for make bundle? At least we need to document what versions of tools are needed

`make bundle` should work for you now

I will document in a following PR, I want to work towards adding HELM, then some docs, then cut release, that's the plan before Feb 🤞🏽

**Comment by marquiz** [comment]
> `make bundle` should work for you now

Hmm 🤨

```
$ make bundle
/home/marquiz/go/git/node-feature-discovery-operator/review/bin/controller-gen "crd" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
operator-sdk generate kustomize manifests -q
Error: unknown shorthand flag: 'q' in -q
Usage:
  operator-sdk generate [command]
...

```

**Comment by ArangoGutierrez** [comment]
> > `make bundle` should work for you now
> 
> Hmm raised_eyebrow
> 
> ```
> $ make bundle
> /home/marquiz/go/git/node-feature-discovery-operator/review/bin/controller-gen "crd" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
> operator-sdk generate kustomize manifests -q
> Error: unknown shorthand flag: 'q' in -q
> Usage:
>   operator-sdk generate [command]
> ...
> ```

[eduardo@fedora rhcos]$ operator-sdk version
operator-sdk version: "v1.26.0-7-ga5d933b5", commit: "a5d933b5e8d729c9c3f9f1790f61053cf37dfafd", kubernetes version: "v1.25.0", go version: "go1.19.5", GOOS: "linux", GOARCH: "amd64"

...?

**Comment by marquiz** [comment]
That was my point. I've have my share of wrong tool/library versions. So could you document e.g. in the commit message what version of operator-sdk was used

**Comment by ArangoGutierrez** [comment]
@marquiz PTAL, commit now includes the version of dependencies to generate the bundle as is in this patch.

**Review by marquiz — COMMENTED** [review]
Thanks @ArangoGutierrez for the update
/lgtm

**Pull request merged**
