### PR TITLE
OWNERS: add ArangoGutierrez as an approver

### PR DESCRIPTION
**Pull request by marquiz**

### CODE REVIEW

**Comment by marquiz** [comment]
@ArangoGutierrez in addition to this PR you need to be member of the kubernetes-sigs org

Apply for membership by filing an issue in [kubernetes/org](https://github.com/kubernetes/org/issues/new/choose).

Before filing an issue, read [this](https://github.com/kubernetes/community/blob/master/community-membership.md) 😄

**Comment by ArangoGutierrez** [comment]
https://github.com/kubernetes/org/issues/2104

**Pull request merged**
