### PR TITLE
Adding prune job to the finalization flow

### PR DESCRIPTION
**Pull request by yevgeny-shnaidman**
1) in case PruneOnDelete defined, prune job is created during
   finalization flow.
2) the finalizer is not deleted from NFD object until prune job is
   completed successfully
3) changing the filtering to responds to events only in case of NFD
   owned objects

### CODE REVIEW

**Comment by yevgeny-shnaidman** [comment]
ping @ArangoGutierrez

**Comment by yevgeny-shnaidman** [comment]
ping @marquiz

**Review by marquiz — APPROVED** [review]
Thanks @yevgeny-shnaidman, looks good

@ArangoGutierrez PTAL

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Pull request merged**
