### PR TITLE
Drop the non-working link from the Advanced section

### LINKED ISSUE #94: Link not working in Advanced section
In https://kubernetes-sigs.github.io/node-feature-discovery-operator/v0.2/advanced/nodefeaturediscovery.html
`For more information about how to setup the WorkerConfig stanza, see worker config reference`, the link is giving 404 Error.

I think there might be some version problem in the redirected link.

### PR DESCRIPTION
**Pull request by Evalle**
PR Summary:
- Drops the non-working link from the Advanced section
- Fixes #94

### CODE REVIEW

**Comment by vaibhav2107** [comment]
@Evalle Thanks for the fix

**Comment by marquiz** [comment]
@Evalle you need to rebase the patch on top of `origin/release-0.2` and then change the  target branch to `release-0.2`

**Comment by Evalle** [comment]
Ok, done, sorry for the mess.

**Pull request merged**
