### PR TITLE
Updated readme of CONTRIBUTION.md

### LINKED ISSUE #164: Broken Link Issue Need to Fix
## Bug Report
*Problem*
[This page ](https://github.com/kubernetes-sigs/node-feature-discovery-operator/blob/master/CONTRIBUTING.md) has one broken link of `contributor cheat sheet` which needs to fix.
 

*solution*
need to locate the correct path of README.

/assign 
/kind bug
/kind documentation

### PR DESCRIPTION
**Pull request by amolmote**
Signed-off-by: amolmote <amolmote201@gmail.com>
Fixes #164

### CODE REVIEW

**Review by marquiz — APPROVED** [review]
Thanks @amolmote for the patch!
/ok-to-test
/lgtm

**Comment by amolmote** [comment]
welcome @marquiz

**Comment by fmuyassarov** [comment]
Hi @amolmote ,
Thanks for the patch. The test failure is unrelated to your patch and should be fixed once we have https://github.com/kubernetes-sigs/node-feature-discovery-operator/pull/163 landed. I will re-trigger the tests once https://github.com/kubernetes-sigs/node-feature-discovery-operator/pull/163 is merged.

**Comment by amolmote** [comment]
Ok now I understand thank you

**Comment by marquiz** [comment]
@amolmote sorry for the hassle. You need to rebase this on top of the latest master in order to get the fixes for the ci step

**Comment by amolmote** [comment]
@marquiz , please guide me for this. Here we have only one commit then how can I rebase, Do I need to change the base branch?

**Comment by fmuyassarov** [comment]
'''
git add upstream https://github.com/kubernetes-sigs/node-feature-discovery-operator
git fetch upstream
git rebase upstream/master
'''

this should do the work

**Comment by marquiz** [comment]
Yeah, that should do it (https://docs.github.com/en/get-started/using-git/about-git-rebase). Alternatively you can also do a git merge.
/retest

**Comment by amolmote** [comment]
@marquiz  have you did it?

**Comment by amolmote** [comment]
I know the procedure to rebase our own multiple commits into single commit.

**Comment by amolmote** [comment]
btw thank you @marquiz

**Comment by marquiz** [comment]
> @marquiz have you did it?

Yeah, I suspected that /retest might do it by merging your PR to master (which has the required fix) and then testing that one. And it did so problem solved 😅

**Pull request merged**
